config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'posts#index'
  get '/', to: 'posts#index', as: 'homepage'
  get '/home', to: 'posts#index'

  resources :authors do
    resources :posts do
      resources :comments, only: %i[new create]
    end
  end
  resources :posts do
    resources :comments, only: [:index]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < User
  has_many :posts, foreign_key: :user_id, inverse_of: :author
  has_many :comments, foreign_key: :user_id, inverse_of: :author

  validates :first_name, presence: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: :user_id, inverse_of: :comments
  belongs_to :post, dependent: :destroy

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: 'user_id', class_name: 'Author', inverse_of: :posts
  has_many :comments, -> { order(created_at: :asc) }

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  rescue
    render_404
  end

  def render_404
    render file: 'public/404.html', status: :not_found, layout: false
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name description])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]
  before_action :set_author, only: %i[edit update destroy]
  # GET /authors/1 or /authors/1.json
  def show
    response = AuthorDisplayService.new({ author_params: params }).call

    not_found and return unless response.success?

    @author = response.author
    @latest_posts = response.latest_posts
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.js
      else
        format.js do
          format.js { render json: @author.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.js
      else
        format.js do
          render json: @author.errors, status: :unprocessable_entity
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def author_params
    params.require(:author).permit(:body, :user_id, :post_id, :first_name, :last_name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_author, only: %i[create]
  before_action :set_post, only: %i[create index]
  before_action :set_comment, only: %i[show edit]

  # GET /comments or /comments.json
  def index
    @comments = @post.comments.page(params[:page] || 1).per(5)
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /comments/1 or /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.js
      else
        format.js { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_author
    @author = current_user
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id, :author_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_author, only: %i[show new]
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).page(params[:page] || 1).per(5)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.page(params[:page] || 1).per(5)
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    respond_to do |format|
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
    respond_to do |format|
      format.js
      format.html { head :not_found }
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.js
      else
        format.js { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_author
    @author = current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def devise_resource
    @devise_resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def ensure_my_profile?(author)
    return false unless current_user

    current_user.id == author.id
  end
end

app/views/authors/_article_box.html.erb
<div class="col-lg-3 col-sm-6 ">
  <div class="card h-100">
    <div class="card-header position-relative">
      <h5 class="card-title">
        <%= link_to post.title, post_path(post) %>
      </h5>
    </div>
    <div class="card-body">
      <p class="card-text"><%= (post.body&.length || 0 ) < 60 ? post.body : truncate(post.body, :length => 60) %></p>
    
      
      <span><%= link_to "Read more", post_path(post) %> </span>
    </div>
    <div class="card-footer text-muted">
      Created: <%= post.created_at&.strftime("%m/%d/%Y") %> <span>
    </div>
  </div>
</div>

app/views/authors/_author_modal.html.erb
<div id="authorModal" class="modal modal-styled fade">

  <div class="modal-dialog">

    <div class="modal-content">

    </div>

  </div>

</div>

app/views/authors/_form.html.erb
<%= form_for author, remote: true do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Author</h3>
  </div>

  <div class="modal-body">
    <div class="form-group row">
      <%= form.label :first_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_field :first_name, id: :first_name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :last_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_field :last_name, id: :first_name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_area :description, id: :description, class: "form-control", required: true%>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
<% end %>

app/views/authors/_info_section.html.erb
<section id="author-info-section" class="py-sm-7 py-5 position-relative">
  <div class="container">
    <div class="row">
      <div class="col-12 mx-auto">
        <div class="row py-5">
          <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h3 class="mb-2"><%= author&.full_name %></h3>
              <div class="d-block">
                <%= link_to 'Edit', edit_author_path(author), remote: true, class: "btn btn-sm btn-outline-info text-nowrap mb-0" if ensure_my_profile?(author)%>
              </div>
            </div>
            <div class="row mb-4">
              <div class="col-auto">
                <span>Email:</span>
                <span class="h6"> <%= author&.email %> </span>
              </div>
            </div>
            <div class="row mb-4">
              <div class="col-auto">
                <span class="h6"> <%= author&.posts&.count %> </span>
                <span>Posts</span>
              </div>
              <div class="col-auto">
                <span class="h6"><%= author&.comments&.count %></span>
                <span>Comments</span>
              </div>
            </div>
            <p class="text-lg mb-0">
              <%= author&.description %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/authors/edit.js.erb
$('#authorModal .modal-content').html('<%= j render partial: "form", locals: { author: @author } %>');
$('#authorModal').modal('show');

app/views/authors/show.html.erb
<div class="col-lg-12 mx-auto">
  <header>
    <div class="page-header min-height-300">
      <span class="mask bg-gradient-dark opacity-8" style="background-image: url('https://i.pinimg.com/originals/6f/3c/be/6f3cbebdc0ec1f5652a9803d8e80e62f.jpg')"></span>
    </div>
  </header>
  <!-- -------- END HEADER 4 w/ search book a ticket form ------- -->
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <!-- START Testimonials w/ user image & text & info -->
    <%= render partial: 'info_section', locals: { author: @author }%>
    <!-- END Testimonials w/ user image & text & info -->
    <!-- START Blogs w/ 4 cards w/ image & text & link -->
    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Check my latest blogposts</h3>
          </div>
        </div>
        <div class="row">
          <%= render partial: 'article_box', collection: @latest_posts, as: :post%>
        </div>
      </div>
    </section>
    <!-- END Blogs w/ 4 cards w/ image & text & link -->
  </div>
</div>
<%= render 'author_modal' %>

app/views/authors/update.js.erb
$('section#author-info-section').replaceWith("<%= j render partial: 'info_section', locals: { author: @author } %>");
$('#authorModal').modal('toggle');

app/views/comments/_comment_item.html.erb
<li class="list-group-item">
  <div class="row">
    <div class="col-lg-3 col-sm-6">
      <p><%= link_to comment.author.full_name.blank? ? comment.author.email : comment.author.full_name, author_path(comment.author)%>: </p>
    </div>
    <div class="col-lg-9 col-sm-6">
      <p><%= comment.body %> <p>
    </div>
    <span style="float: right;">Created on: <%= comment.created_at&.strftime("%m/%d/%Y at %I:%M%p") %> <span>
  </div>
</li>

app/views/comments/_comment_section.html.erb
<div id="comments-section">
<p id="notice"><%= notice %></p>
<h3>Comments</h3>
<div class="row">
  <ul id="comments-list" class="list-group list-group-flush">
    <%= render partial: 'comments/comment_item', collection: comments, as: :comment%>
  </ul>
  <br>
  <span class="float: right"><%= paginate comments, remote: true if comments%> </span>
  <p>Add comment</p>
  <%= render partial: 'comments/form', locals: { author: post.author, post: post, comment: Comment.new } %>
</div>
<div>

app/views/comments/_form.html.erb
<%= form_for [author, post, comment], remote: true do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, id: 'comment-text-area-input', class: "form-control"%>
    <%= form.hidden_field :user_id, value: author.id%>
    <%= form.hidden_field :post_id, value: post.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments-list').append("<%= j render partial: 'comment_item', locals: { comment: @comment } %>");
$('#comment-text-area-input').val('');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.js.erb
$('#comments-section').replaceWith("<%= j render partial: 'comment_section', locals: { post: @post, comments: @comments} %>");
$('#authorModal').modal('toggle');

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrivityCodeProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/sessions_modal'%>
    <%= render 'layouts/theme/nav_bar'%>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/theme/footer'%>
  </body>
</html>

app/views/layouts/theme/_footer.html.erb
<footer class="footer py-5">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto text-center mt-1">
          <p class="mb-0 text-secondary">
            Copyright © 2022 Nick Dos Santos.
          </p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/theme/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-gradient-dark py-3">
  <div class="container">
    <a class="navbar-brand" href="/" data-placement="bottom">
      Brivity Code Project
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon mt-2">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </span>
    </button>
    <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
      <ul class="navbar-nav navbar-nav-hover ms-auto">
        <li class="nav-item dropdown dropdown-hover mx-2">
          <%= link_to "Posts", posts_path, class: "nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" %>
        </li>
        <li class="nav-item dropdown dropdown-hover mx-2">
          <%= link_to "Profile", author_path(current_user), class: "nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" if current_user%>
        </li>
        <li class="nav-item ms-lg-auto">
          <a class="nav-link nav-link-icon me-2" href="https://github.com/nickdossantos/brivity_code_project" target="_blank">
            <i class="fa fa-github me-1" aria-hidden="true"></i>
            <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Star us on Github">Github</p>
          </a>
        </li>
        <li class="nav-item my-auto ms-3 ms-lg-0">
          <%if user_signed_in?%>
          <li class="nav-item mx-2">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-sm  bg-gradient-primary  mb-0 me-1" %>
          </li>
          <% else %>
            <li class="nav-item mx-2">
              <%= link_to "Sign In", new_user_session_path, class: "btn btn-sm  bg-gradient-primary ps-2 d-flex", remote: true%>
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_comments_section.html.erb
<%= render_async post_comments_path(post) %>
<p>Add comment</p>

<%= render partial: 'comments/form', locals: { author: post.author, post: post, comment: Comment.new } %>

app/views/posts/_comments_section_old.html.erb
<%= render_async post_comments_path(post) %>
<p>Add comment</p>

<%= render partial: 'comments/form', locals: { author: post.author, post: post, comment: Comment.new } %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: false) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" name="_method" id="form-method" value=""/>

  <div class="modal-header">
    <h3 class="modal-title text-center">Post</h3>
  </div>

  <div class="modal-body">
    <div class="form-group row">
      <%= form.label :title, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_field :title, id: :post_title, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= form.text_area :body, id: :post_body, class: "form-control", required: true%>
      </div>
    </div>
  </div>

  <%= form.hidden_field :user_id, value: author&.id%>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
<% end %>

app/views/posts/_post_item.html.erb
<li class="list-group-item" data-link-path="<%= post_path(post) %>">
  <div class="text-center">
    <h5 class="mx-auto"><%= link_to post.title, post_path(post) %><h5>
  </div>
  <p><%= post.body %> <p>
  <p>Created By: <%= link_to post.author.full_name.blank? ? post.author.email : post.author.full_name, author_path(post.author)%> </p>
  <%= link_to 'View More', post_path(post) %>
  <span style="float: right;">Created on: <%= post.created_at&.strftime("%m/%d/%Y at %I:%M%p")  %> <span>
</li>

app/views/posts/_post_modal.html.erb
<div class="modal" id="postModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">

    <div class="modal-content">

    </div>

  </div>
</div>

app/views/posts/create.js.erb
$('#post-list').append("<%= j render partial: 'post_item', locals: { post: @post } %>");
$('#postModal').modal('toggle');

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="col-lg-8 mx-auto">
  <p id="notice"><%= notice %></p>
  <div class="card card-body">
    <ul id="post-list" class="list-group list-group-flush">
      <%= render partial: 'post_item', collection: @posts, as: :post%>
    </ul>
    <br>
    
    <p><%= link_to 'New Post', new_author_post_path(current_user.id), remote: true  if current_user%><p>
  </div>
  <%= paginate @posts%>
  <%= render 'post_modal' %>
<div>

app/views/posts/new.js.erb
$('#postModal .modal-content').html('<%= j render partial: "form", locals: { post: @post, author: @author} %>');
$('#postModal').modal('show');

app/views/posts/show.html.erb
<div class="col-lg-8 mx-auto">
  <p id="notice"><%= notice %></p>
  <h2 class="text-center"> <%= @post.title %> </h2>
  <br>
  <p> <%= @post.body %> </p>
  <p>
    <strong>Created by:</strong>
    <%= link_to @post.author.full_name, author_path(@post.author) %>
    <span style="float: right;">Created on: <%= @post.created_at&.strftime("%m/%d/%Y") %> <span>
  </p>
  
  <hr>
  <%= render partial: 'comments/comment_section', locals: { post: @post, comments: @comments }%>
</div>

app/views/posts/show.js.erb
$('#comments-section').replaceWith("<%= j render partial: 'comments/comment_section', locals: { post: @post, comments: @comments} %>");

app/views/shared/_sessions_modal.html.erb
<div id="sessionsModal" class="modal modal-styled fade">

  <div class="modal-dialog">

    <div class="modal-content">

    </div>

  </div>

</div>